# Generated by Django 6.0 on 2025-12-16 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0008_warehouse_allow_negative_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('affects_stock', models.BooleanField(default=True)),
                ('affects_financial', models.BooleanField(default=False)),
                ('direction', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída'), ('TRF', 'Transferência')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movement_types_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movement_types_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Movement Type',
                'verbose_name_plural': 'Stock Movement Types',
                'db_table': 'stock_movement_type',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('movement_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.warehouse')),
                ('movement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stockmovementtype')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'stock_movement',
            },
        ),
        migrations.CreateModel(
            name='StockMovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.stockmovement')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='masterdata.productvariant')),
            ],
            options={
                'verbose_name': 'Stock Movement Item',
                'verbose_name_plural': 'Stock Movement Items',
                'db_table': 'stock_movement_item',
                'indexes': [models.Index(fields=['product_variant'], name='stock_movem_product_7ca573_idx'), models.Index(fields=['movement'], name='stock_movem_movemen_48beb6_idx')],
            },
        ),
    ]