# Generated by Django 6.0 on 2025-12-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_paymentmethod_pricetable_customer_product_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pricetable',
            table='price_table',
        ),
    ]
