# Generated by Django 6.0 on 2025-12-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_alter_pricetable_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
