# Generated by Django 6.0 on 2025-12-16 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_alter_customer_options_alter_customer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attribute',
            table='attribute',
        ),
        migrations.AlterModelTable(
            name='attributevalue',
            table='attribute_value',
        ),
        migrations.AlterModelTable(
            name='pricetableitem',
            table='price_table_item',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productvariant',
            table='product_variant',
        ),
        migrations.AlterModelTable(
            name='unit',
            table='unit',
        ),
        migrations.AlterModelTable(
            name='warehouse',
            table='warehouse',
        ),
    ]
