# Generated by Django 6.0 on 2025-12-16 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_alter_attribute_table_alter_attributevalue_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariantattribute',
            name='uq_product_variant_attribute_product_attribute',
        ),
        migrations.AddConstraint(
            model_name='productvariantattribute',
            constraint=models.UniqueConstraint(fields=('product_variant', 'attribute', 'attribute_value'), name='uq_product_variant_attribute_product_attribute_value'),
        ),
    ]
