# Generated by Django 6.0 on 2025-12-16 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_remove_productvariantattribute_uq_product_variant_attribute_product_attribute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariantattribute',
            name='uq_product_variant_attribute_product_attribute_value',
        ),
        migrations.AddConstraint(
            model_name='productvariantattribute',
            constraint=models.UniqueConstraint(fields=('product_variant', 'attribute'), name='uq_product_variant_attribute_product_attribute_value'),
        ),
    ]
