# Generated by Django 6.0 on 2025-12-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0007_remove_productvariantattribute_uq_product_variant_attribute_product_attribute_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='allow_negative_stock',
            field=models.BooleanField(default=False),
        ),
    ]
