# Generated by Django 6.0 on 2025-12-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_city_is_active_country_is_active_state_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
        migrations.AlterModelTable(
            name='state',
            table='state',
        ),
    ]
